/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        tertiary: '#d3e4fe',
        'surface-container-low': '#131b2e',
        'error-container': '#93000a',
        'secondary-fixed-dim': '#bcc7de',
        'on-primary-fixed': '#001a42',
        error: '#ffb4ab',
        'surface-container-high': '#222a3d',
        'primary-container': '#adc6ff',
        'on-primary-container': '#385283',
        surface: '#0b1326',
        'surface-container-lowest': '#060e20',
        'on-tertiary-fixed-variant': '#38485d',
        'on-secondary-fixed': '#111c2d',
        'surface-container-highest': '#303541',
        'on-secondary': '#263143',
        'on-background': '#dee2f2',
        'on-error-container': '#ffdad6',
        'outline-variant': '#424754',
        outline: '#8c909f',
        'surface-container': '#171f33',
        'on-secondary-container': '#aab5cc',
        'tertiary-fixed': '#d3e4fe',
        'on-primary': '#122f5f',
        'on-secondary-fixed-variant': '#3c475a',
        'inverse-surface': '#dee2f2',
        'surface-variant': '#303541',
        'primary-fixed': '#d8e2ff',
        'inverse-primary': '#455e90',
        'on-surface': '#dee2f2',
        primary: '#d8e2ff',
        'secondary-container': '#3c475a',
        'primary-accent-alt': '#3B82F6',
        'on-tertiary-container': '#435469',
        'surface-dim': '#0f131e',
        background: '#0f131e',
        'on-tertiary': '#213145',
        'on-primary-fixed-variant': '#2c4677',
        'on-surface-variant': '#c4c6d0',
        'tertiary-container': '#b7c8e1',
        'surface-bright': '#353946',
        'primary-fixed-dim': '#adc6ff',
        secondary: '#bcc7de',
        'tertiary-fixed-dim': '#b7c8e1',
        'inverse-on-surface': '#2c303d',
        'on-tertiary-fixed': '#0b1c2f',
        'secondary-fixed': '#d8e3fa',
        'surface-tint': '#adc6ff',
        'on-error': '#690005',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        rhythm: '8px',
        xl: '32px',
        sm: '8px',
        '2xl': '48px',
        md: '16px',
        lg: '24px',
        margin: '32px',
        'base-unit': '4px',
        xs: '4px',
        gutter: '24px',
      },
      fontFamily: {
        inter: ['Inter', 'sans-serif'],
        'body-md': ['Inter'],
        'label-sm': ['Inter'],
        'body-lg': ['Inter'],
        h3: ['Inter'],
        h2: ['Inter'],
        h1: ['Inter'],
        'label-md': ['Inter'],
      },
      fontSize: {
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.03em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '400' }],
        h3: ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        h2: ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '600' }],
        h1: ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
